---
- name: Deploy NGINX on RHEL10
  hosts: rhel10
  become: true

  tasks:

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Open firewall for HTTP
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Deploy custom index page
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
          <h1>Welcome from AAP Automation</h1>
          <h2>Enterprise NGINX Deployment Successful</h2>
          </html>

    - name: Validate nginx
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200
