---
- name: Patch RHEL9 Servers
  hosts: foreman_content_view_rhl9
  become: true
  serial: 2

  tasks:

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true

    - name: Check reboot requirement
      ansible.builtin.command:
        cmd: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: false

    - name: Reboot if required
      ansible.builtin.reboot:
        reboot_timeout: 1800
      when: reboot_required.rc != 0

    - name: Validate connectivity
      ansible.builtin.ping:
